Update AllureRunner.yml

diff --git a/.github/workflows/AllureRunner.yml b/.github/workflows/AllureRunner.yml
--- a/.github/workflows/AllureRunner.yml
+++ b/.github/workflows/AllureRunner.yml
@@ -34,8 +34,8 @@ jobs:
         if: always()
         continue-on-error: true
         run: |
-           newman run Postman-Collections/Postman-Collections.json --reporters cli,allure
-           echo "Postman tests run."
+          newman run Postman-Collections/Postman-Collections.json --reporters cli,allure
+          echo "Postman tests run."
 
       - name: Get Allure history
         uses: actions/checkout@v2
@@ -75,7 +75,7 @@ jobs:
       - name: Wait for Allure report to be generated
         if: always()
         continue-on-error: true
-        run: sleep 60
+        run: sleep 120
 
       - name: Find new folder in gh-pages
         id: new_folder
@@ -96,6 +96,16 @@ jobs:
             exit 1
           else
             echo "New folder number ($new_folder_number) is greater than current latest folder number ($current_latest_number)."
+          fi
+
+      - name: Verify new folder exists
+        run: |
+          new_folder_number=${{ steps.new_folder.outputs.new_folder_number }}
+          if [ -d "gh-pages/$new_folder_number" ]; then
+            echo "New folder gh-pages/$new_folder_number created successfully."
+          else
+            echo "Error: New folder gh-pages/$new_folder_number was not created."
+            exit 1
           fi
 
       - name: List contents of new folder
@@ -155,18 +165,18 @@ jobs:
             echo "::set-output name=failed_tests::0"
           fi
 
-      - name: Notify Slack
-        if: always()
-        uses: rtCamp/action-slack-notify@v2
-        env:
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-          SLACK_CHANNEL: 'C070KUKPDLZ'
-          SLACK_MESSAGE: |
-            *Eatcheffie Vendor - API Quality Readiness*
-            *Contributors - Moses George*
-            Status: ${{ job.status }}
-            Passing Tests: ${{ steps.parse_new_json.outputs.passing_percentage }}%
-            Failing Tests: ${{ steps.parse_new_json.outputs.failing_percentage }}%
-            Total Passed: ${{ steps.parse_new_json.outputs.passed_tests }}
-            Total Failed: ${{ steps.parse_new_json.outputs.failed_tests }}
-            GitHub Pages URL: ${{ secrets.PAGES_URL }}/${{ steps.new_folder.outputs.new_folder_number }}
+      # - name: Notify Slack
+      #   if: always()
+      #   uses: rtCamp/action-slack-notify@v2
+      #   env:
+      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+      #     SLACK_CHANNEL: 'C070KUKPDLZ'
+      #     SLACK_MESSAGE: |
+      #       *Eatcheffie Vendor - API Quality Readiness*
+      #       *Contributors - Moses George*
+      #       Status: ${{ job.status }}
+      #       Passing Tests: ${{ steps.parse_new_json.outputs.passing_percentage }}%
+      #       Failing Tests: ${{ steps.parse_new_json.outputs.failing_percentage }}%
+      #       Total Passed: ${{ steps.parse_new_json.outputs.passed_tests }}
+      #       Total Failed: ${{ steps.parse_new_json.outputs.failed_tests }}
+      #       GitHub Pages URL: ${{ secrets.PAGES_URL }}/${{ steps.new_folder.outputs.new_folder_number }}
